### PR TITLE
add `for_url_str` receive &str as a argument

### PR DESCRIPTION
**Pull request by cssivision**
format code with `rls` and fix issue https://github.com/inejge/env_proxy/issues/2.

### CODE REVIEW

**Comment by cssivision** [comment]
i will update the pr, if there is something is not what you want.

**Comment by inejge** [comment]
Thanks for the PR, but I'm afraid that I can't accept it as is, chiefly because it introduces a breaking change -- different public function signature -- without bumping the version of the crate according to the Rust interpretation of semver. (Aside from that, I prefer when the changes of this magnitude are broken up in a series of smaller commits, which makes reviewing easier.) I only have intermittent internet access atm so I can't offer a detailed review. I'll try to get back to this sometime next week.

**Comment by cssivision** [comment]
update this pr, introducing `for_url_str` instead of change the existed `for_url`.

**Comment by ordian** [comment]
Can we please merge this and release a new version? See [rustup workaround](https://github.com/rust-lang-nursery/rustup.rs/blob/08300345c2b67e75adc22376420a7a1cd09dbc44/src/download/src/lib.rs#L306-L313) and https://github.com/killercup/cargo-edit/pull/179.

**Comment by inejge** [comment]
I've neglected this PR; guilty! Thank you for pointing me to workarounds in other code, they gave me an idea how to restructure the API while keeping breakage to a minimum. (Code coming soon, although I'm rather busy atm.)

**Comment by ordian** [comment]
Thank you!

**Pull request merged**
